name: Build Node

on: [push]

# on:
#   push:
#     tags:
#       - 'v[0-9]+.*'      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'
        run: |
          npm ci
          npm run build
          ls ./dist
          ls ./dist/libs
          ls ./dist/nodes
          ls ./dist/icons

