name: Build Node

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if package.json version has changed
        id: version_changed
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "package.json" || true)
          if [ -n "$CHANGED" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Build if version changed
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          npm ci
          npm run build

