name: Build Node

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
      - uses: actions/checkout@v4
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'
          
      - name: Install dependencies      
      - run: npm ci
      - run: npm run build
